-- AlterTable
ALTER TABLE `PostSeedFund` ADD COLUMN `file1` VARCHAR(191) NULL,
    ADD COLUMN `file2` VARCHAR(191) NULL,
    ADD COLUMN `file3` VARCHAR(191) NULL,
    ADD COLUMN `file4` VARCHAR(191) NULL;
