const userData = () => {
  const users = [
    { id: 1, companyName: "HealthTech Solutions" }, // Alice Johnson
    { id: 2, companyName: "HealthTech Solutions" }, // Bob Brown
    { id: 3, companyName: "FinTech Innovators" }, // Charlie Green
    { id: 4, companyName: "FinTech Innovators" }, // Diana White
    { id: 5, companyName: "EdTech Platform" }, // Emily Taylor
    { id: 6, companyName: "EdTech Platform" }, // Frank Wilson
    { id: 7, companyName: "RealEstate Connect" }, // George Martin
    { id: 9, companyName: "RealEstate Connect" }, // Hannah Lee
    { id: 10, companyName: "AgriTech Innovations" }, // Ivy Parker
    { id: 11, companyName: "CleanEnergy Solutions" }, // Jack Hill
    { id: 12, companyName: "SmartHome Technologies" },
  ];

  const userDetails = {
    1: {
      registrationNumber: "10111213",
      founderName: "Alice Johnson",
      founderAadharNumber: "1111-2222-3333",
      cofunderName: "Bob Brown",
      cofunderAadharNumber: "4444-5555-6666",
      sector: "Healthcare",
      briefOnBusinessConcept:
        "A health tech company providing telemedicine services.",
      mobileNo: "9876543210",
      email: "contact@healthtech.com",
      companyLogo: "health_logo.png",
      websiteLink: "https://www.healthtech.com",
      category: "Health Services",
      gender: "Female",
      dpiitRecognitionNumber: "DPIIT101112",
      dippCertificate: "health_dipp_certificate.pdf",
      iprApplied: "Yes",
      companyName: "HealthTech Solutions",
      dateOfIncorporation: "2020-05-15",
      businessEntityType: "Private Limited",
      companyCertificate: "health_company_certificate.pdf",
      rocDistrict: "Bangalore",
      companyAddress: "123 Health St, Bangalore",
      pincode: "560001",
      bankName: "State Bank of India",
      ifscCode: "SBIN0000123",
      currentAccountNumber: "1234567890",
      currentAccountHolderName: "HealthTech Solutions Pvt Ltd",
      branchName: "MG Road Branch",
      branchAddress: "MG Road, Bangalore",
      cancelledCheque: "health_cancelled_cheque.png",
      panNumber: "AABCH1234F",
      utilizationCertificate: "health_utilization_certificate.pdf",
      statusReport: "health_status_report.pdf",
      secondTrancheExpenditurePlan: "health_expenditure_plan.pdf",
      bankStatement: "health_bank_statement.pdf",
      expenditureInvoice: "health_expenditure_invoice.pdf",
      geoTaggedPhotos: "health_geo_photos.zip",
    },
    2: {
      registrationNumber: "14151617",
      founderName: "Charlie Green",
      founderAadharNumber: "7777-8888-9999",
      cofunderName: "Diana White",
      cofunderAadharNumber: "0000-1111-2222",
      sector: "Finance",
      briefOnBusinessConcept:
        "A fintech company offering digital payment solutions.",
      mobileNo: "1234567890",
      email: "contact@fintech.com",
      companyLogo: "fintech_logo.png",
      websiteLink: "https://www.fintech.com",
      category: "Financial Services",
      gender: "Male",
      dpiitRecognitionNumber: "DPIIT141516",
      dippCertificate: "fintech_dipp_certificate.pdf",
      iprApplied: "Yes",
      companyName: "FinTech Innovators",
      dateOfIncorporation: "2018-07-22",
      businessEntityType: "LLP",
      companyCertificate: "fintech_company_certificate.pdf",
      rocDistrict: "Mumbai",
      companyAddress: "456 Finance Lane, Mumbai",
      pincode: "400001",
      bankName: "ICICI Bank",
      ifscCode: "ICIC0000123",
      currentAccountNumber: "9876543210",
      currentAccountHolderName: "FinTech Innovators LLP",
      branchName: "Nariman Point Branch",
      branchAddress: "Nariman Point, Mumbai",
      cancelledCheque: "fintech_cancelled_cheque.png",
      panNumber: "AACFG1234P",
      utilizationCertificate: "fintech_utilization_certificate.pdf",
      statusReport: "fintech_status_report.pdf",
      secondTrancheExpenditurePlan: "fintech_expenditure_plan.pdf",
      bankStatement: "fintech_bank_statement.pdf",
      expenditureInvoice: "fintech_expenditure_invoice.pdf",
      geoTaggedPhotos: "fintech_geo_photos.zip",
    },
    3: {
      registrationNumber: "18192021",
      founderName: "Emily Taylor",
      founderAadharNumber: "3333-4444-5555",
      cofunderName: "Frank Wilson",
      cofunderAadharNumber: "6666-7777-8888",
      sector: "Education",
      briefOnBusinessConcept: "An ed-tech platform providing online courses.",
      mobileNo: "4567890123",
      email: "contact@edtech.com",
      companyLogo: "edtech_logo.png",
      websiteLink: "https://www.edtech.com",
      category: "E-learning",
      gender: "Female",
      dpiitRecognitionNumber: "DPIIT181920",
      dippCertificate: "edtech_dipp_certificate.pdf",
      iprApplied: "No",
      companyName: "EdTech Platform",
      dateOfIncorporation: "2019-03-12",
      businessEntityType: "Private Limited",
      companyCertificate: "edtech_company_certificate.pdf",
      rocDistrict: "Hyderabad",
      companyAddress: "789 Edu St, Hyderabad",
      pincode: "500001",
      bankName: "Axis Bank",
      ifscCode: "AXIS0001234",
      currentAccountNumber: "5678901234",
      currentAccountHolderName: "EdTech Platform Pvt Ltd",
      branchName: "Hitech City Branch",
      branchAddress: "Hitech City, Hyderabad",
      cancelledCheque: "edtech_cancelled_cheque.png",
      panNumber: "AACDE5678K",
      utilizationCertificate: "edtech_utilization_certificate.pdf",
      statusReport: "edtech_status_report.pdf",
      secondTrancheExpenditurePlan: "edtech_expenditure_plan.pdf",
      bankStatement: "edtech_bank_statement.pdf",
      expenditureInvoice: "edtech_expenditure_invoice.pdf",
      geoTaggedPhotos: "edtech_geo_photos.zip",
    },
    4: {
      registrationNumber: "22232425",
      founderName: "George Martin",
      founderAadharNumber: "9999-0000-1111",
      cofunderName: "Hannah Lee",
      cofunderAadharNumber: "2222-3333-4444",
      sector: "Real Estate",
      briefOnBusinessConcept:
        "A real estate platform connecting buyers and sellers.",
      mobileNo: "7890123456",
      email: "contact@realestate.com",
      companyLogo: "realestate_logo.png",
      websiteLink: "https://www.realestate.com",
      category: "Property Management",
      gender: "Male",
      dpiitRecognitionNumber: "DPIIT222324",
      dippCertificate: "realestate_dipp_certificate.pdf",
      iprApplied: "Yes",
      companyName: "RealEstate Connect",
      dateOfIncorporation: "2017-11-02",
      businessEntityType: "LLP",
      companyCertificate: "realestate_company_certificate.pdf",
      rocDistrict: "Chennai",
      companyAddress: "321 Realty Lane, Chennai",
      pincode: "600001",
      bankName: "HDFC Bank",
      ifscCode: "HDFC0009876",
      currentAccountNumber: "6543210987",
      currentAccountHolderName: "RealEstate Connect LLP",
      branchName: "Anna Salai Branch",
      branchAddress: "Anna Salai, Chennai",
      cancelledCheque: "realestate_cancelled_cheque.png",
      panNumber: "AAECG1234D",
      utilizationCertificate: "realestate_utilization_certificate.pdf",
      statusReport: "realestate_status_report.pdf",
      secondTrancheExpenditurePlan: "realestate_expenditure_plan.pdf",
      bankStatement: "realestate_bank_statement.pdf",
      expenditureInvoice: "realestate_expenditure_invoice.pdf",
      geoTaggedPhotos: "realestate_geo_photos.zip",
    },
    5: {
      registrationNumber: "26272829",
      founderName: "Ivy Parker",
      founderAadharNumber: "5555-6666-7777",
      cofunderName: "Jack Hill",
      cofunderAadharNumber: "8888-9999-0000",
      sector: "Agriculture",
      briefOnBusinessConcept:
        "An agri-tech startup using AI for crop monitoring.",
      mobileNo: "3456789012",
      email: "contact@agritech.com",
      companyLogo: "agritech_logo.png",
      websiteLink: "https://www.agritech.com",
      category: "Agriculture Technology",
      gender: "Female",
      dpiitRecognitionNumber: "DPIIT262728",
      dippCertificate: "agritech_dipp_certificate.pdf",
      iprApplied: "Yes",
      companyName: "AgriTech Innovations",
      dateOfIncorporation: "2021-09-20",
      businessEntityType: "Private Limited",
      companyCertificate: "agritech_company_certificate.pdf",
      rocDistrict: "Pune",
      companyAddress: "456 Agro Rd, Pune",
      pincode: "411001",
      bankName: "Bank of Baroda",
      ifscCode: "BARB0000987",
      currentAccountNumber: "1231231234",
      currentAccountHolderName: "AgriTech Innovations Pvt Ltd",
      branchName: "FC Road Branch",
      branchAddress: "FC Road, Pune",
      cancelledCheque: "agritech_cancelled_cheque.png",
      panNumber: "AAGPI1234M",
      utilizationCertificate: "agritech_utilization_certificate.pdf",
      statusReport: "agritech_status_report.pdf",
      secondTrancheExpenditurePlan: "yup",
    },
    6: {
      registrationNumber: "30313233",
      founderName: "Liam Johnson",
      founderAadharNumber: "1111-2222-4444",
      cofunderName: "Mia Brown",
      cofunderAadharNumber: "5555-6666-7777",
      sector: "Fashion",
      briefOnBusinessConcept:
        "An online clothing store offering sustainable fashion.",
      mobileNo: "6543217890",
      email: "contact@sustainablefashion.com",
      companyLogo: "fashion_logo.png",
      websiteLink: "https://www.sustainablefashion.com",
      category: "E-commerce",
      gender: "Male",
      dpiitRecognitionNumber: "DPIIT303132",
      dippCertificate: "fashion_dipp_certificate.pdf",
      iprApplied: "Yes",
    },
    7: {
      registrationNumber: "34353637",
      founderName: "Noah Davis",
      founderAadharNumber: "8888-0000-1111",
      cofunderName: "Olivia Miller",
      cofunderAadharNumber: "2222-3333-4444",
      sector: "Travel",
      briefOnBusinessConcept: "A travel agency specializing in eco-tours.",
      mobileNo: "3219876540",
      email: "contact@ecotravel.com",
      companyLogo: "travel_logo.png",
      websiteLink: "https://www.ecotravel.com",
      category: "Tourism",
      gender: "Male",
      dpiitRecognitionNumber: "DPIIT343536",
      dippCertificate: "travel_dipp_certificate.pdf",
      iprApplied: "No",
    },
    8: {
      registrationNumber: "38394041",
      founderName: "Sophia Wilson",
      founderAadharNumber: "5555-6666-7777",
      cofunderName: "James Brown",
      cofunderAadharNumber: "8888-9999-0000",
      sector: "Fitness",
      briefOnBusinessConcept:
        "A fitness app providing personalized workout plans.",
      mobileNo: "9870123456",
      email: "contact@fitapp.com",
      companyLogo: "fitapp_logo.png",
      websiteLink: "https://www.fitapp.com",
      category: "Health & Fitness",
      gender: "Female",
      dpiitRecognitionNumber: "DPIIT383940",
      dippCertificate: "fitapp_dipp_certificate.pdf",
      iprApplied: "Yes",
    },
    9: {
      registrationNumber: "42434445",
      founderName: "Ethan Taylor",
      founderAadharNumber: "0000-1111-2222",
      cofunderName: "Ava Jackson",
      cofunderAadharNumber: "3333-4444-5555",
      sector: "Gaming",
      briefOnBusinessConcept:
        "A game development studio creating mobile games.",
      mobileNo: "5678901234",
      email: "contact@gamestudio.com",
      companyLogo: "gamestudio_logo.png",
      websiteLink: "https://www.gamestudio.com",
      category: "Entertainment",
      gender: "Male",
      dpiitRecognitionNumber: "DPIIT424344",
      dippCertificate: "gamestudio_dipp_certificate.pdf",
      iprApplied: "No",
    },
    10: {
      registrationNumber: "46474849",
      founderName: "Mason Brown",
      founderAadharNumber: "6666-7777-8888",
      cofunderName: "Isabella Davis",
      cofunderAadharNumber: "9999-0000-1111",
      sector: "Automotive",
      briefOnBusinessConcept:
        "An automotive company focusing on electric vehicles.",
      mobileNo: "2109876543",
      email: "contact@autotech.com",
      companyLogo: "autotech_logo.png",
      websiteLink: "https://www.autotech.com",
      category: "Automotive Services",
      gender: "Male",
      dpiitRecognitionNumber: "DPIIT464748",
      dippCertificate: "autotech_dipp_certificate.pdf",
      iprApplied: "Yes",
    },

    11: {
      registrationNumber: "12345678",
      founderName: "John Doe",
      founderAadharNumber: "1234-5678-9012",
      cofunderName: "Jane Smith",
      cofunderAadharNumber: "2345-6789-0123",
      sector: "Technology",
      briefOnBusinessConcept:
        "A tech company focused on innovative software solutions.",
      mobileNo: "9876543210",
      email: "contact@abccorp.com",
      companyLogo: "logo.png",
      websiteLink: "https://www.abccorp.com",
      category: "IT Services",
      gender: "Male",
      dpiitRecognitionNumber: "DPIIT123456",
      dippCertificate: "dipp_certificate.pdf",
      iprApplied: "Yes",
    },
    12: {
      registrationNumber: "87654321",
      founderName: "Jane Smith",
      founderAadharNumber: "2345-6789-0123",
      cofunderName: "John Doe",
      cofunderAadharNumber: "1234-5678-9012",
      sector: "Retail",
      briefOnBusinessConcept: "An e-commerce platform for selling products.",
      mobileNo: "1234567890",
      email: "contact@xyzpvtltd.com",
      companyLogo: "xyz_logo.png",
      websiteLink: "https://www.xyzpvtltd.com",
      category: "E-commerce",
      gender: "Female",
      dpiitRecognitionNumber: "DPIIT987654",
      dippCertificate: "xyz_dipp_certificate.pdf",
      iprApplied: "No",
    },
  };
  return { users, userDetails };
};
export default userData;
